// AUTO-GENERATED by scripts/build-prefectures.ts. DO NOT EDIT.
export interface Prefecture {
  adcode: number;
  code: string;       // "c{adcode}" — 与现有手工 50 城的 code 命名空间区分
  name: string;
  province: string;
  region: string;
  level: string;      // "city" | "district" 等（直辖市为 province）
}

export const PREFECTURES: Prefecture[] = [
  {
    "adcode": 110000,
    "code": "c110000",
    "name": "北京市",
    "province": "北京市",
    "region": "华北",
    "level": "province"
  },
  {
    "adcode": 120000,
    "code": "c120000",
    "name": "天津市",
    "province": "天津市",
    "region": "华北",
    "level": "province"
  },
  {
    "adcode": 310000,
    "code": "c310000",
    "name": "上海市",
    "province": "上海市",
    "region": "华东",
    "level": "province"
  },
  {
    "adcode": 500000,
    "code": "c500000",
    "name": "重庆市",
    "province": "重庆市",
    "region": "西南",
    "level": "province"
  },
  {
    "adcode": 130100,
    "code": "c130100",
    "name": "石家庄市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130200,
    "code": "c130200",
    "name": "唐山市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130300,
    "code": "c130300",
    "name": "秦皇岛市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130400,
    "code": "c130400",
    "name": "邯郸市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130500,
    "code": "c130500",
    "name": "邢台市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130600,
    "code": "c130600",
    "name": "保定市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130700,
    "code": "c130700",
    "name": "张家口市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130800,
    "code": "c130800",
    "name": "承德市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 130900,
    "code": "c130900",
    "name": "沧州市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 131000,
    "code": "c131000",
    "name": "廊坊市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 131100,
    "code": "c131100",
    "name": "衡水市",
    "province": "河北省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140100,
    "code": "c140100",
    "name": "太原市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140200,
    "code": "c140200",
    "name": "大同市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140300,
    "code": "c140300",
    "name": "阳泉市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140400,
    "code": "c140400",
    "name": "长治市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140500,
    "code": "c140500",
    "name": "晋城市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140600,
    "code": "c140600",
    "name": "朔州市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140700,
    "code": "c140700",
    "name": "晋中市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140800,
    "code": "c140800",
    "name": "运城市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 140900,
    "code": "c140900",
    "name": "忻州市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 141000,
    "code": "c141000",
    "name": "临汾市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 141100,
    "code": "c141100",
    "name": "吕梁市",
    "province": "山西省",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150100,
    "code": "c150100",
    "name": "呼和浩特市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150200,
    "code": "c150200",
    "name": "包头市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150300,
    "code": "c150300",
    "name": "乌海市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150400,
    "code": "c150400",
    "name": "赤峰市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150500,
    "code": "c150500",
    "name": "通辽市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150600,
    "code": "c150600",
    "name": "鄂尔多斯市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150700,
    "code": "c150700",
    "name": "呼伦贝尔市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150800,
    "code": "c150800",
    "name": "巴彦淖尔市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 150900,
    "code": "c150900",
    "name": "乌兰察布市",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 152200,
    "code": "c152200",
    "name": "兴安盟",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 152500,
    "code": "c152500",
    "name": "锡林郭勒盟",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 152900,
    "code": "c152900",
    "name": "阿拉善盟",
    "province": "内蒙古自治区",
    "region": "华北",
    "level": "city"
  },
  {
    "adcode": 210100,
    "code": "c210100",
    "name": "沈阳市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210200,
    "code": "c210200",
    "name": "大连市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210300,
    "code": "c210300",
    "name": "鞍山市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210400,
    "code": "c210400",
    "name": "抚顺市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210500,
    "code": "c210500",
    "name": "本溪市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210600,
    "code": "c210600",
    "name": "丹东市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210700,
    "code": "c210700",
    "name": "锦州市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210800,
    "code": "c210800",
    "name": "营口市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 210900,
    "code": "c210900",
    "name": "阜新市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 211000,
    "code": "c211000",
    "name": "辽阳市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 211100,
    "code": "c211100",
    "name": "盘锦市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 211200,
    "code": "c211200",
    "name": "铁岭市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 211300,
    "code": "c211300",
    "name": "朝阳市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 211400,
    "code": "c211400",
    "name": "葫芦岛市",
    "province": "辽宁省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220100,
    "code": "c220100",
    "name": "长春市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220200,
    "code": "c220200",
    "name": "吉林市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220300,
    "code": "c220300",
    "name": "四平市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220400,
    "code": "c220400",
    "name": "辽源市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220500,
    "code": "c220500",
    "name": "通化市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220600,
    "code": "c220600",
    "name": "白山市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220700,
    "code": "c220700",
    "name": "松原市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 220800,
    "code": "c220800",
    "name": "白城市",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 222400,
    "code": "c222400",
    "name": "延边朝鲜族自治州",
    "province": "吉林省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230100,
    "code": "c230100",
    "name": "哈尔滨市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230200,
    "code": "c230200",
    "name": "齐齐哈尔市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230300,
    "code": "c230300",
    "name": "鸡西市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230400,
    "code": "c230400",
    "name": "鹤岗市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230500,
    "code": "c230500",
    "name": "双鸭山市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230600,
    "code": "c230600",
    "name": "大庆市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230700,
    "code": "c230700",
    "name": "伊春市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230800,
    "code": "c230800",
    "name": "佳木斯市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 230900,
    "code": "c230900",
    "name": "七台河市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 231000,
    "code": "c231000",
    "name": "牡丹江市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 231100,
    "code": "c231100",
    "name": "黑河市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 231200,
    "code": "c231200",
    "name": "绥化市",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 232700,
    "code": "c232700",
    "name": "大兴安岭地区",
    "province": "黑龙江省",
    "region": "东北",
    "level": "city"
  },
  {
    "adcode": 320100,
    "code": "c320100",
    "name": "南京市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320200,
    "code": "c320200",
    "name": "无锡市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320300,
    "code": "c320300",
    "name": "徐州市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320400,
    "code": "c320400",
    "name": "常州市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320500,
    "code": "c320500",
    "name": "苏州市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320600,
    "code": "c320600",
    "name": "南通市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320700,
    "code": "c320700",
    "name": "连云港市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320800,
    "code": "c320800",
    "name": "淮安市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 320900,
    "code": "c320900",
    "name": "盐城市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 321000,
    "code": "c321000",
    "name": "扬州市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 321100,
    "code": "c321100",
    "name": "镇江市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 321200,
    "code": "c321200",
    "name": "泰州市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 321300,
    "code": "c321300",
    "name": "宿迁市",
    "province": "江苏省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330100,
    "code": "c330100",
    "name": "杭州市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330200,
    "code": "c330200",
    "name": "宁波市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330300,
    "code": "c330300",
    "name": "温州市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330400,
    "code": "c330400",
    "name": "嘉兴市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330500,
    "code": "c330500",
    "name": "湖州市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330600,
    "code": "c330600",
    "name": "绍兴市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330700,
    "code": "c330700",
    "name": "金华市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330800,
    "code": "c330800",
    "name": "衢州市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 330900,
    "code": "c330900",
    "name": "舟山市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 331000,
    "code": "c331000",
    "name": "台州市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 331100,
    "code": "c331100",
    "name": "丽水市",
    "province": "浙江省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340100,
    "code": "c340100",
    "name": "合肥市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340200,
    "code": "c340200",
    "name": "芜湖市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340300,
    "code": "c340300",
    "name": "蚌埠市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340400,
    "code": "c340400",
    "name": "淮南市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340500,
    "code": "c340500",
    "name": "马鞍山市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340600,
    "code": "c340600",
    "name": "淮北市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340700,
    "code": "c340700",
    "name": "铜陵市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 340800,
    "code": "c340800",
    "name": "安庆市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341000,
    "code": "c341000",
    "name": "黄山市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341100,
    "code": "c341100",
    "name": "滁州市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341200,
    "code": "c341200",
    "name": "阜阳市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341300,
    "code": "c341300",
    "name": "宿州市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341500,
    "code": "c341500",
    "name": "六安市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341600,
    "code": "c341600",
    "name": "亳州市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341700,
    "code": "c341700",
    "name": "池州市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 341800,
    "code": "c341800",
    "name": "宣城市",
    "province": "安徽省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350100,
    "code": "c350100",
    "name": "福州市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350200,
    "code": "c350200",
    "name": "厦门市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350300,
    "code": "c350300",
    "name": "莆田市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350400,
    "code": "c350400",
    "name": "三明市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350500,
    "code": "c350500",
    "name": "泉州市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350600,
    "code": "c350600",
    "name": "漳州市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350700,
    "code": "c350700",
    "name": "南平市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350800,
    "code": "c350800",
    "name": "龙岩市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 350900,
    "code": "c350900",
    "name": "宁德市",
    "province": "福建省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 360100,
    "code": "c360100",
    "name": "南昌市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360200,
    "code": "c360200",
    "name": "景德镇市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360300,
    "code": "c360300",
    "name": "萍乡市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360400,
    "code": "c360400",
    "name": "九江市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360500,
    "code": "c360500",
    "name": "新余市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360600,
    "code": "c360600",
    "name": "鹰潭市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360700,
    "code": "c360700",
    "name": "赣州市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360800,
    "code": "c360800",
    "name": "吉安市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 360900,
    "code": "c360900",
    "name": "宜春市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 361000,
    "code": "c361000",
    "name": "抚州市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 361100,
    "code": "c361100",
    "name": "上饶市",
    "province": "江西省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 370100,
    "code": "c370100",
    "name": "济南市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370200,
    "code": "c370200",
    "name": "青岛市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370300,
    "code": "c370300",
    "name": "淄博市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370400,
    "code": "c370400",
    "name": "枣庄市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370500,
    "code": "c370500",
    "name": "东营市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370600,
    "code": "c370600",
    "name": "烟台市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370700,
    "code": "c370700",
    "name": "潍坊市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370800,
    "code": "c370800",
    "name": "济宁市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 370900,
    "code": "c370900",
    "name": "泰安市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371000,
    "code": "c371000",
    "name": "威海市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371100,
    "code": "c371100",
    "name": "日照市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371300,
    "code": "c371300",
    "name": "临沂市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371400,
    "code": "c371400",
    "name": "德州市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371500,
    "code": "c371500",
    "name": "聊城市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371600,
    "code": "c371600",
    "name": "滨州市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 371700,
    "code": "c371700",
    "name": "菏泽市",
    "province": "山东省",
    "region": "华东",
    "level": "city"
  },
  {
    "adcode": 410100,
    "code": "c410100",
    "name": "郑州市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410200,
    "code": "c410200",
    "name": "开封市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410300,
    "code": "c410300",
    "name": "洛阳市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410400,
    "code": "c410400",
    "name": "平顶山市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410500,
    "code": "c410500",
    "name": "安阳市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410600,
    "code": "c410600",
    "name": "鹤壁市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410700,
    "code": "c410700",
    "name": "新乡市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410800,
    "code": "c410800",
    "name": "焦作市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 410900,
    "code": "c410900",
    "name": "濮阳市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411000,
    "code": "c411000",
    "name": "许昌市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411100,
    "code": "c411100",
    "name": "漯河市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411200,
    "code": "c411200",
    "name": "三门峡市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411300,
    "code": "c411300",
    "name": "南阳市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411400,
    "code": "c411400",
    "name": "商丘市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411500,
    "code": "c411500",
    "name": "信阳市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411600,
    "code": "c411600",
    "name": "周口市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 411700,
    "code": "c411700",
    "name": "驻马店市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 419001,
    "code": "c419001",
    "name": "济源市",
    "province": "河南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420100,
    "code": "c420100",
    "name": "武汉市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420200,
    "code": "c420200",
    "name": "黄石市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420300,
    "code": "c420300",
    "name": "十堰市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420500,
    "code": "c420500",
    "name": "宜昌市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420600,
    "code": "c420600",
    "name": "襄阳市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420700,
    "code": "c420700",
    "name": "鄂州市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420800,
    "code": "c420800",
    "name": "荆门市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 420900,
    "code": "c420900",
    "name": "孝感市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 421000,
    "code": "c421000",
    "name": "荆州市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 421100,
    "code": "c421100",
    "name": "黄冈市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 421200,
    "code": "c421200",
    "name": "咸宁市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 421300,
    "code": "c421300",
    "name": "随州市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 422800,
    "code": "c422800",
    "name": "恩施土家族苗族自治州",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 429004,
    "code": "c429004",
    "name": "仙桃市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 429005,
    "code": "c429005",
    "name": "潜江市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 429006,
    "code": "c429006",
    "name": "天门市",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 429021,
    "code": "c429021",
    "name": "神农架林区",
    "province": "湖北省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430100,
    "code": "c430100",
    "name": "长沙市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430200,
    "code": "c430200",
    "name": "株洲市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430300,
    "code": "c430300",
    "name": "湘潭市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430400,
    "code": "c430400",
    "name": "衡阳市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430500,
    "code": "c430500",
    "name": "邵阳市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430600,
    "code": "c430600",
    "name": "岳阳市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430700,
    "code": "c430700",
    "name": "常德市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430800,
    "code": "c430800",
    "name": "张家界市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 430900,
    "code": "c430900",
    "name": "益阳市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 431000,
    "code": "c431000",
    "name": "郴州市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 431100,
    "code": "c431100",
    "name": "永州市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 431200,
    "code": "c431200",
    "name": "怀化市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 431300,
    "code": "c431300",
    "name": "娄底市",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 433100,
    "code": "c433100",
    "name": "湘西土家族苗族自治州",
    "province": "湖南省",
    "region": "华中",
    "level": "city"
  },
  {
    "adcode": 440100,
    "code": "c440100",
    "name": "广州市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440200,
    "code": "c440200",
    "name": "韶关市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440300,
    "code": "c440300",
    "name": "深圳市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440400,
    "code": "c440400",
    "name": "珠海市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440500,
    "code": "c440500",
    "name": "汕头市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440600,
    "code": "c440600",
    "name": "佛山市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440700,
    "code": "c440700",
    "name": "江门市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440800,
    "code": "c440800",
    "name": "湛江市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 440900,
    "code": "c440900",
    "name": "茂名市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441200,
    "code": "c441200",
    "name": "肇庆市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441300,
    "code": "c441300",
    "name": "惠州市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441400,
    "code": "c441400",
    "name": "梅州市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441500,
    "code": "c441500",
    "name": "汕尾市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441600,
    "code": "c441600",
    "name": "河源市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441700,
    "code": "c441700",
    "name": "阳江市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441800,
    "code": "c441800",
    "name": "清远市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 441900,
    "code": "c441900",
    "name": "东莞市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 442000,
    "code": "c442000",
    "name": "中山市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 445100,
    "code": "c445100",
    "name": "潮州市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 445200,
    "code": "c445200",
    "name": "揭阳市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 445300,
    "code": "c445300",
    "name": "云浮市",
    "province": "广东省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450100,
    "code": "c450100",
    "name": "南宁市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450200,
    "code": "c450200",
    "name": "柳州市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450300,
    "code": "c450300",
    "name": "桂林市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450400,
    "code": "c450400",
    "name": "梧州市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450500,
    "code": "c450500",
    "name": "北海市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450600,
    "code": "c450600",
    "name": "防城港市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450700,
    "code": "c450700",
    "name": "钦州市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450800,
    "code": "c450800",
    "name": "贵港市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 450900,
    "code": "c450900",
    "name": "玉林市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 451000,
    "code": "c451000",
    "name": "百色市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 451100,
    "code": "c451100",
    "name": "贺州市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 451200,
    "code": "c451200",
    "name": "河池市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 451300,
    "code": "c451300",
    "name": "来宾市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 451400,
    "code": "c451400",
    "name": "崇左市",
    "province": "广西壮族自治区",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 460100,
    "code": "c460100",
    "name": "海口市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 460200,
    "code": "c460200",
    "name": "三亚市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 460300,
    "code": "c460300",
    "name": "三沙市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 460400,
    "code": "c460400",
    "name": "儋州市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469001,
    "code": "c469001",
    "name": "五指山市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469002,
    "code": "c469002",
    "name": "琼海市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469005,
    "code": "c469005",
    "name": "文昌市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469006,
    "code": "c469006",
    "name": "万宁市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469007,
    "code": "c469007",
    "name": "东方市",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469021,
    "code": "c469021",
    "name": "定安县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469022,
    "code": "c469022",
    "name": "屯昌县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469023,
    "code": "c469023",
    "name": "澄迈县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469024,
    "code": "c469024",
    "name": "临高县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469025,
    "code": "c469025",
    "name": "白沙黎族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469026,
    "code": "c469026",
    "name": "昌江黎族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469027,
    "code": "c469027",
    "name": "乐东黎族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469028,
    "code": "c469028",
    "name": "陵水黎族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469029,
    "code": "c469029",
    "name": "保亭黎族苗族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 469030,
    "code": "c469030",
    "name": "琼中黎族苗族自治县",
    "province": "海南省",
    "region": "华南",
    "level": "city"
  },
  {
    "adcode": 510100,
    "code": "c510100",
    "name": "成都市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510300,
    "code": "c510300",
    "name": "自贡市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510400,
    "code": "c510400",
    "name": "攀枝花市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510500,
    "code": "c510500",
    "name": "泸州市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510600,
    "code": "c510600",
    "name": "德阳市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510700,
    "code": "c510700",
    "name": "绵阳市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510800,
    "code": "c510800",
    "name": "广元市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 510900,
    "code": "c510900",
    "name": "遂宁市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511000,
    "code": "c511000",
    "name": "内江市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511100,
    "code": "c511100",
    "name": "乐山市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511300,
    "code": "c511300",
    "name": "南充市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511400,
    "code": "c511400",
    "name": "眉山市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511500,
    "code": "c511500",
    "name": "宜宾市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511600,
    "code": "c511600",
    "name": "广安市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511700,
    "code": "c511700",
    "name": "达州市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511800,
    "code": "c511800",
    "name": "雅安市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 511900,
    "code": "c511900",
    "name": "巴中市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 512000,
    "code": "c512000",
    "name": "资阳市",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 513200,
    "code": "c513200",
    "name": "阿坝藏族羌族自治州",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 513300,
    "code": "c513300",
    "name": "甘孜藏族自治州",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 513400,
    "code": "c513400",
    "name": "凉山彝族自治州",
    "province": "四川省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520100,
    "code": "c520100",
    "name": "贵阳市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520200,
    "code": "c520200",
    "name": "六盘水市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520300,
    "code": "c520300",
    "name": "遵义市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520400,
    "code": "c520400",
    "name": "安顺市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520500,
    "code": "c520500",
    "name": "毕节市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 520600,
    "code": "c520600",
    "name": "铜仁市",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 522300,
    "code": "c522300",
    "name": "黔西南布依族苗族自治州",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 522600,
    "code": "c522600",
    "name": "黔东南苗族侗族自治州",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 522700,
    "code": "c522700",
    "name": "黔南布依族苗族自治州",
    "province": "贵州省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530100,
    "code": "c530100",
    "name": "昆明市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530300,
    "code": "c530300",
    "name": "曲靖市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530400,
    "code": "c530400",
    "name": "玉溪市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530500,
    "code": "c530500",
    "name": "保山市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530600,
    "code": "c530600",
    "name": "昭通市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530700,
    "code": "c530700",
    "name": "丽江市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530800,
    "code": "c530800",
    "name": "普洱市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 530900,
    "code": "c530900",
    "name": "临沧市",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 532300,
    "code": "c532300",
    "name": "楚雄彝族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 532500,
    "code": "c532500",
    "name": "红河哈尼族彝族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 532600,
    "code": "c532600",
    "name": "文山壮族苗族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 532800,
    "code": "c532800",
    "name": "西双版纳傣族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 532900,
    "code": "c532900",
    "name": "大理白族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 533100,
    "code": "c533100",
    "name": "德宏傣族景颇族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 533300,
    "code": "c533300",
    "name": "怒江傈僳族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 533400,
    "code": "c533400",
    "name": "迪庆藏族自治州",
    "province": "云南省",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540100,
    "code": "c540100",
    "name": "拉萨市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540200,
    "code": "c540200",
    "name": "日喀则市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540300,
    "code": "c540300",
    "name": "昌都市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540400,
    "code": "c540400",
    "name": "林芝市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540500,
    "code": "c540500",
    "name": "山南市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 540600,
    "code": "c540600",
    "name": "那曲市",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 542500,
    "code": "c542500",
    "name": "阿里地区",
    "province": "西藏自治区",
    "region": "西南",
    "level": "city"
  },
  {
    "adcode": 610100,
    "code": "c610100",
    "name": "西安市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610200,
    "code": "c610200",
    "name": "铜川市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610300,
    "code": "c610300",
    "name": "宝鸡市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610400,
    "code": "c610400",
    "name": "咸阳市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610500,
    "code": "c610500",
    "name": "渭南市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610600,
    "code": "c610600",
    "name": "延安市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610700,
    "code": "c610700",
    "name": "汉中市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610800,
    "code": "c610800",
    "name": "榆林市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 610900,
    "code": "c610900",
    "name": "安康市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 611000,
    "code": "c611000",
    "name": "商洛市",
    "province": "陕西省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620100,
    "code": "c620100",
    "name": "兰州市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620200,
    "code": "c620200",
    "name": "嘉峪关市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620300,
    "code": "c620300",
    "name": "金昌市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620400,
    "code": "c620400",
    "name": "白银市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620500,
    "code": "c620500",
    "name": "天水市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620600,
    "code": "c620600",
    "name": "武威市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620700,
    "code": "c620700",
    "name": "张掖市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620800,
    "code": "c620800",
    "name": "平凉市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 620900,
    "code": "c620900",
    "name": "酒泉市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 621000,
    "code": "c621000",
    "name": "庆阳市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 621100,
    "code": "c621100",
    "name": "定西市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 621200,
    "code": "c621200",
    "name": "陇南市",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 622900,
    "code": "c622900",
    "name": "临夏回族自治州",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 623000,
    "code": "c623000",
    "name": "甘南藏族自治州",
    "province": "甘肃省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 630100,
    "code": "c630100",
    "name": "西宁市",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 630200,
    "code": "c630200",
    "name": "海东市",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632200,
    "code": "c632200",
    "name": "海北藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632300,
    "code": "c632300",
    "name": "黄南藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632500,
    "code": "c632500",
    "name": "海南藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632600,
    "code": "c632600",
    "name": "果洛藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632700,
    "code": "c632700",
    "name": "玉树藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 632800,
    "code": "c632800",
    "name": "海西蒙古族藏族自治州",
    "province": "青海省",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 640100,
    "code": "c640100",
    "name": "银川市",
    "province": "宁夏回族自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 640200,
    "code": "c640200",
    "name": "石嘴山市",
    "province": "宁夏回族自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 640300,
    "code": "c640300",
    "name": "吴忠市",
    "province": "宁夏回族自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 640400,
    "code": "c640400",
    "name": "固原市",
    "province": "宁夏回族自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 640500,
    "code": "c640500",
    "name": "中卫市",
    "province": "宁夏回族自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 650100,
    "code": "c650100",
    "name": "乌鲁木齐市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 650200,
    "code": "c650200",
    "name": "克拉玛依市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 650400,
    "code": "c650400",
    "name": "吐鲁番市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 650500,
    "code": "c650500",
    "name": "哈密市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 652300,
    "code": "c652300",
    "name": "昌吉回族自治州",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 652700,
    "code": "c652700",
    "name": "博尔塔拉蒙古自治州",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 652800,
    "code": "c652800",
    "name": "巴音郭楞蒙古自治州",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 652900,
    "code": "c652900",
    "name": "阿克苏地区",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 653000,
    "code": "c653000",
    "name": "克孜勒苏柯尔克孜自治州",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 653100,
    "code": "c653100",
    "name": "喀什地区",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 653200,
    "code": "c653200",
    "name": "和田地区",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 654000,
    "code": "c654000",
    "name": "伊犁哈萨克自治州",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 654200,
    "code": "c654200",
    "name": "塔城地区",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 654300,
    "code": "c654300",
    "name": "阿勒泰地区",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659001,
    "code": "c659001",
    "name": "石河子市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659002,
    "code": "c659002",
    "name": "阿拉尔市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659003,
    "code": "c659003",
    "name": "图木舒克市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659004,
    "code": "c659004",
    "name": "五家渠市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659005,
    "code": "c659005",
    "name": "北屯市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659006,
    "code": "c659006",
    "name": "铁门关市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659007,
    "code": "c659007",
    "name": "双河市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659008,
    "code": "c659008",
    "name": "可克达拉市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659009,
    "code": "c659009",
    "name": "昆玉市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  },
  {
    "adcode": 659010,
    "code": "c659010",
    "name": "胡杨河市",
    "province": "新疆维吾尔自治区",
    "region": "西北",
    "level": "city"
  }
];
